name: Build

on:
  push:
    tags:
      - 'v*' 
      
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - run: pip install pyinstaller
    - run: pyinstaller -w -F nyaa.py
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*
